version: '2'
services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes_from:
      - files
      - php
    links:
      - php
  php:
    build: .
    volumes_from:
      - files
  files:
    image: busybox
    volumes:
      - .:/var/www/html
